### ISSUE TITLE
examples/cdk-application-pipeline build synth failed

### ISSUE THREAD

**Issue by ADF1111** [aws-samples/aws-deployment-pipeline-reference-architecture#20]
Hello,

I have deployed cdk application example (examples/cdk-application-pipeline). After I bootstrapped the accounts, I ran `npx cdk deploy --profile default --all --require-appr never`. Once it finished, AWS CodePipeline failed in Synth status (see screenshots). Alejandro Moncayo helped me to fix it running `npx jest --updateSnapshot`. The pipeline is now running again.

![Screenshot 2023-06-29 at 17 49 15](https://github.com/aws-samples/aws-deployment-pipeline-reference-architecture/assets/80117876/7bc66d28-3572-4238-9c32-779f3e85d3f5)

![Screenshot 2023-06-29 at 17 44 59](https://github.com/aws-samples/aws-deployment-pipeline-reference-architecture/assets/80117876/0b227612-37c0-4550-82a4-f54a08559781)

**Comment by cplee** [comment]
@ADF1111 - do you have the output from what failed in the snapshot? It would be further back in the logs before the test summary that you shared.
